name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the binary
        run: |
          # Add your build commands here
          cargo build --release  # Example for Rust

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: x64/Release/Quick Sound Endpoint Switcher.exe  # Specify the path to your binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
